//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public int TrafficId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string ID { get; set; }
        public string IPAddress { get; set; }
    }
}
